/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlAdministrador;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Administrador;

/**
 *
 * @author Windows 10
 */
public class vistaMenuAdministradorCrearAdmin extends javax.swing.JFrame {

    /**
     * Creates new form vistaMenuAdministradorCrearAdmin
     */
    public vistaMenuAdministradorCrearAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        direccionAdmin = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        contraseñaAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nom1Admin = new javax.swing.JTextField();
        txtfoton = new javax.swing.JTextField();
        nom2Admin = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ape1Admin = new javax.swing.JTextField();
        ape2Admin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        correoAdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 960));
        setMinimumSize(new java.awt.Dimension(540, 960));
        setPreferredSize(new java.awt.Dimension(540, 960));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(540, 960));
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 960));
        jPanel1.setLayout(null);
        jPanel1.add(direccionAdmin);
        direccionAdmin.setBounds(80, 560, 380, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-04.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 20, 70, 70);

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Correo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 480, 220, 15);
        jPanel1.add(contraseñaAdmin);
        contraseñaAdmin.setBounds(80, 630, 380, 30);

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 540, 240, 15);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BTN-log-VENDEDOR-02.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 780, 270, 73);

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 610, 250, 15);

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("Foto");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 670, 80, 20);

        nom1Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1AdminActionPerformed(evt);
            }
        });
        jPanel1.add(nom1Admin);
        nom1Admin.setBounds(80, 260, 380, 30);
        jPanel1.add(txtfoton);
        txtfoton.setBounds(220, 700, 244, 30);
        jPanel1.add(nom2Admin);
        nom2Admin.setBounds(80, 320, 380, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 8)); // NOI18N
        jButton2.setText("AGREGAR FOTO");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 700, 120, 30);
        jPanel1.add(ape1Admin);
        ape1Admin.setBounds(80, 380, 380, 30);
        jPanel1.add(ape2Admin);
        ape2Admin.setBounds(80, 440, 380, 30);

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Nombre2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 300, 100, 15);

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Nombre1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 230, 120, 30);

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Apellido1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 360, 240, 15);
        jPanel1.add(correoAdmin);
        correoAdmin.setBounds(80, 500, 380, 30);

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Apellido2");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 420, 240, 15);

        jLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSERTAR ADMINISTRADOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 180, 380, 30);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgAdmin-01.png"))); // NOI18N
        jPanel1.add(Back);
        Back.setBounds(0, 0, 540, 960);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 960);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nom1AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom1AdminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here

        Administrador ad= new Administrador();
        ad.setNom1Admin(nom1Admin.getText());
        ad.setNom2Admin(nom2Admin.getText());
        ad.setApe1Admin(ape1Admin.getText());
        ad.setApe2Admin(ape2Admin.getText());
        ad.setCorreoAdmin(correoAdmin.getText());
        ad.setDireccionAdmin(direccionAdmin.getText());
        ad.setContraseñaAdmin(contraseñaAdmin.getText());
        File rutaFotoProducto = new File(txtfoton.getText());

        try{
            byte[] foto = new byte[(int) rutaFotoProducto.length()];
            InputStream input = new FileInputStream(rutaFotoProducto);
            input.read(foto);
            ad.setFotoAdmin(foto);
        }catch(Exception ex){
            ad.setFotoAdmin(null);
        }

        ControlAdministrador  objAdmin =new ControlAdministrador();
        boolean t = objAdmin.insertarAdministrador(ad);

        if(t==true){
            JOptionPane.showMessageDialog(rootPane, "Se insertó el nuevo administrador");
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se insertó el nuevo administrador");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        j.setFileFilter(fil);

        int s = j.showOpenDialog(this);
        if(s == JFileChooser.APPROVE_OPTION){
            String ruta = j.getSelectedFile().getAbsolutePath();
            txtfoton.setText(ruta);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        vistaMenuAdministrador v = new vistaMenuAdministrador();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorCrearAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorCrearAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorCrearAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorCrearAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaMenuAdministradorCrearAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JTextField ape1Admin;
    private javax.swing.JTextField ape2Admin;
    private javax.swing.JTextField contraseñaAdmin;
    private javax.swing.JTextField correoAdmin;
    private javax.swing.JTextField direccionAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nom1Admin;
    private javax.swing.JTextField nom2Admin;
    private javax.swing.JTextField txtfoton;
    // End of variables declaration//GEN-END:variables
}
