/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlTienda;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import modelo.Tienda;

/**
 *
 * @author Windows 10
 */
public class vistaMenuAdministradorTiendaConsultar extends javax.swing.JFrame {

    /**
     * Creates new form vistaAdministradorTiendaConsultar
     */
    
    LinkedList<Tienda> listaTiendas;
    LinkedList<Tienda> listaTiendas2;
    public static String idAdmin;
    
    public vistaMenuAdministradorTiendaConsultar() {
        initComponents();
        listaTiendas = new LinkedList<>();
        listaTiendas2 = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 960));
        setMinimumSize(new java.awt.Dimension(540, 960));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(540, 960));
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 960));
        jPanel1.setLayout(null);
        jPanel1.add(txtId);
        txtId.setBounds(40, 320, 360, 30);

        jTable1.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idTienda", "nomTienda", "direccionTienda", "fotoTienda", "descripcionTienda", "aprobacionTienda", "fechaAprobacionTienda", "idAdminTF", "identificacionCVF", "idFotoPredeterminadaTF"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 430, 460, 340);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdminTiendaConsultarR-02.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(160, 820, 220, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-04.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 20, 70, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdminTiendaConsultar-03.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 310, 90, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdminTiendaConsultarRr-03-03.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 220, 170, 50);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdminTiendaConsultarRr-03-02.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(180, 220, 170, 50);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdminTiendaConsultar-02.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(30, 220, 170, 50);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgAdminTiendaConsultar-01.png"))); // NOI18N
        jPanel1.add(Back);
        Back.setBounds(0, 0, 540, 960);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        vistaMenuAdministrador v = new vistaMenuAdministrador();
        v.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String criterioBusqueda ="hola";
        ControlTienda objcc = new ControlTienda();
        int ncol;
        Object[] fila;
        if (criterioBusqueda != null) {
            listaTiendas = objcc.consultarTiendaNoApro();

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            modelo.addColumn("idTienda");
            modelo.addColumn("nomTienda");
            modelo.addColumn("direccionTienda");
//            modelo.addColumn("fotoTienda");
            modelo.addColumn("descripcionTienda");
//            modelo.addColumn("aprobacionTienda");
            modelo.addColumn("fechaAprobacionTienda");
            modelo.addColumn("idAdminTF");
            modelo.addColumn("identificacionCVF");
            modelo.addColumn("idFotoPredeterminadaTF");
            ncol = modelo.getColumnCount();

            //Object[] fila = new Object[ncol];
            for (int i = 0; i < listaTiendas.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaTiendas.get(i).getIdTienda();
                fila[1] = listaTiendas.get(i).getNomTienda();
                fila[2] = listaTiendas.get(i).getDireccionTienda();
//                fila[3] = listaTiendas.get(i).getFotoTienda();
                fila[3] = listaTiendas.get(i).getDescripcionTienda();
//                fila[5] = listaTiendas.get(i).getAprobacionTienda();
                fila[4] = listaTiendas.get(i).getFechaAprobacionTienda();
                fila[5] = listaTiendas.get(i).getIdAdminTF();
                fila[6] = listaTiendas.get(i).getIdentificacionCVF();
                fila[7] = listaTiendas.get(i).getIdFotoPredeterminadaTF();
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String criterioBusqueda = txtId.getText();
        ControlTienda objcc = new ControlTienda();
        int ncol=10;
        Object[] fila;
        
        if (criterioBusqueda!=null) {
            listaTiendas2= objcc.consultarTiendas2(criterioBusqueda);
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            modelo.addColumn("idTienda");
            modelo.addColumn("nomTienda");
            modelo.addColumn("direccionTienda");
//            modelo.addColumn("fotoTienda");
            modelo.addColumn("descripcionTienda");
            modelo.addColumn("aprobacionTienda");
            modelo.addColumn("fechaAprobacionTienda");
            modelo.addColumn("identificacionCVF");
            ncol = modelo.getColumnCount();
            
            //Object[] fila = new Object[ncol];
            for (int i = 0; i < listaTiendas2.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaTiendas2.get(i).getIdTienda();
                fila[1] = listaTiendas2.get(i).getNomTienda();
                fila[2] = listaTiendas2.get(i).getDireccionTienda();
                fila[3] = listaTiendas2.get(i).getDescripcionTienda();
                fila[4] = listaTiendas2.get(i).getAprobacionTienda();
                fila[5] = listaTiendas2.get(i).getFechaAprobacionTienda();
                fila[6] = listaTiendas2.get(i).getIdentificacionCVF();
                modelo.addRow(fila);
            }

        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        vistaMenuAdministradorTiendaModificar v = new vistaMenuAdministradorTiendaModificar();
        v.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        ControlTienda objcc = new ControlTienda();
        int ncol;
        Object[] fila;
        listaTiendas = objcc.consultarTiendas();

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            modelo.addColumn("idTienda");
            modelo.addColumn("nomTienda");
            modelo.addColumn("direccionTienda");
            modelo.addColumn("fotoTienda");
            modelo.addColumn("descripcionTienda");
            modelo.addColumn("aprobacionTienda");
            modelo.addColumn("fechaAprobacionTienda");
            modelo.addColumn("idAdminTF");
            modelo.addColumn("identificacionCVF");
            modelo.addColumn("idFotoPredeterminadaTF");
            ncol = modelo.getColumnCount();

            //Object[] fila = new Object[ncol];
            for (int i = 0; i < listaTiendas.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaTiendas.get(i).getIdTienda();
                fila[1] = listaTiendas.get(i).getNomTienda();
                fila[2] = listaTiendas.get(i).getDireccionTienda();
                fila[3] = listaTiendas.get(i).getFotoTienda();
                fila[4] = listaTiendas.get(i).getDescripcionTienda();
                fila[5] = listaTiendas.get(i).getAprobacionTienda();
                fila[6] = listaTiendas.get(i).getFechaAprobacionTienda();
                fila[7] = listaTiendas.get(i).getIdAdminTF();
                fila[8] = listaTiendas.get(i).getIdentificacionCVF();
                fila[9] = listaTiendas.get(i).getIdFotoPredeterminadaTF();
                modelo.addRow(fila);}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String criterioBusqueda ="hola";
        ControlTienda objcc = new ControlTienda();
        int ncol;
        Object[] fila;
        if (criterioBusqueda != null) {
            listaTiendas = objcc.consultarTiendaApro();

            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            modelo.addColumn("idTienda");
            modelo.addColumn("nomTienda");
            modelo.addColumn("direccionTienda");
//            modelo.addColumn("fotoTienda");
            modelo.addColumn("descripcionTienda");
//            modelo.addColumn("aprobacionTienda");
            modelo.addColumn("fechaAprobacionTienda");
            modelo.addColumn("idAdminTF");
            modelo.addColumn("identificacionCVF");
            modelo.addColumn("idFotoPredeterminadaTF");
            ncol = modelo.getColumnCount();

            //Object[] fila = new Object[ncol];
            for (int i = 0; i < listaTiendas.size(); i++) {
                fila = new Object[ncol];
                fila[0] = listaTiendas.get(i).getIdTienda();
                fila[1] = listaTiendas.get(i).getNomTienda();
                fila[2] = listaTiendas.get(i).getDireccionTienda();
//                fila[3] = listaTiendas.get(i).getFotoTienda();
                fila[3] = listaTiendas.get(i).getDescripcionTienda();
//                fila[5] = listaTiendas.get(i).getAprobacionTienda();
                fila[4] = listaTiendas.get(i).getFechaAprobacionTienda();
                fila[5] = listaTiendas.get(i).getIdAdminTF();
                fila[6] = listaTiendas.get(i).getIdentificacionCVF();
                fila[7] = listaTiendas.get(i).getIdFotoPredeterminadaTF();
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorTiendaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorTiendaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorTiendaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMenuAdministradorTiendaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaMenuAdministradorTiendaConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
